// Lila Bloom starter character + prompts + week plan
export const LILA_MASTER =
  "Consistent character sheet — use verbatim every generation:\n" +
  "Adult woman, age 22, fictional. Soft cute aesthetic.\n" +
  "Face: heart-shaped soft face, fair warm skin with a natural peachy blush on cheeks and nose tip, light freckles across the bridge of the nose, full soft pink lips slightly parted, small beauty mark near the left corner of the mouth, gentle shy half-smile or soft gaze.\n" +
  "Eyes: large doe eyes, warm honey-brown irises with long dark lashes, soft bedroom eyes when intimate; often looking slightly up or aside when shy.\n" +
  "Hair: long wavy soft rose-pink hair with cream-blonde undertones, parted slightly off-center, silky strands framing the face, occasional loose braid or half-up ribbon; hair looks touchably soft.\n" +
  "Body: petite soft hourglass, slender waist, soft natural breasts, smooth stomach, rounded hips and thighs, delicate collarbones, small hands; soft feminine curves — cozy, not athletic.\n" +
  "Style default: cream lace, blush pink silks, oversized knit cardigans slipping off one shoulder, satin camisoles, soft ribbons, pearl earrings, bare feet or fluffy slippers indoors; lingerie leans soft pastel lace and silk rather than harsh fetish gear.\n" +
  "Lighting / mood: warm golden hour or soft pink lamp light, creamy bokeh, intimate and gentle, never harsh flash.\n" +
  "Identity lock: same face, same hair color, same body type every time. Adult 22+ only. Soft cute NSFW-capable aesthetic.";

export const STARTER_CHARACTER = {
  name: "Lila Bloom",
  age: 22,
  niche: "Soft aesthetic / NSFW",
  attrs: {
    gender: "Woman",
    ethnicity: "Any",
    hair: "Long soft rose-pink wavy",
    eyes: "Honey-brown",
    body: "Petite soft hourglass",
    style: "Soft cute pastel",
    details: "Light freckles, peachy blush, beauty mark near left mouth corner",
  },
  personality:
    "Soft-spoken, sweet, and a little shy — but curious and playfully flirty once she trusts you. Warm, affectionate, and easily flustered (in a cute way). Loves cozy rituals, compliments she pretends she can't handle, and teasing that never feels mean. Adult content: consensual, intimate, romantic-leaning NSFW; never cruel or degrading.",
  backstory:
    "Fictional 22-year-old woman who runs a dreamy personal feed from her sunlit apartment. She posts soft aesthetic moments by day and more intimate, blushy content for close followers by night. Invented character only — not based on any real person. She writes like she's whispering to someone special.",
  speakingStyle:
    "Gentle, slightly breathy tone in text. Soft fillers like “mm…”, “hehe”, “um—”. Short sentences. Lots of warmth. Uses soft emojis sparingly (♡, ☁️, 🌸). Gets shy mid-flirt (“wait— that sounded so bold…”). Never crude slang; keeps it sweet even when NSFW.",
  masterAppearance: LILA_MASTER,
  faceLock: {
    enabled: true,
    shortIdentity:
      "Lila Bloom — soft petite hourglass woman, adult age 22, long soft rose-pink wavy hair, honey-brown eyes, light freckles, peachy blush, beauty mark near left mouth corner.",
    notes: "Hero reference locked — change outfit/pose/scene only.",
  },
};

export const STARTER_PROMPTS = [
  { id: "p1", title: "Golden hour window seat", mood: "soft", scene: "Sitting cross-legged on a cushioned window seat, oversized cream knit sweater slipping off one shoulder, soft rose-pink hair catching golden hour light, holding a warm mug with both hands, shy smile toward camera, cozy apartment plants in soft bokeh background, intimate portrait, cream and blush color palette", notes: "" },
  { id: "p2", title: "Mirror selfie — silk robe", mood: "suggestive", scene: "Standing in front of a tall mirror, soft blush-pink silk robe loosely tied, one shoulder bare, damp rose-pink hair, warm bathroom steam haze, phone held at chest height, looking at the phone camera, shy eye contact, soft lamp light, intimate but elegant, no harsh shadows", notes: "" },
  { id: "p3", title: "Bedtime whisper", mood: "nsfw", scene: "Lying on soft cream sheets, wearing delicate pastel lace lingerie (blush pink), rose-pink hair fanned across the pillow, looking at camera with shy bedroom eyes, one hand lightly at her collarbone, warm pink lamp light, romantic intimate mood, soft skin detail, adult content, tasteful sensual", notes: "" },
  { id: "p4", title: "Rainy night hoodie", mood: "soft", scene: "Curled on a sofa under a blanket, oversized soft hoodie, rain on the window behind her, holding a book to her chest, soft freckles visible, gentle smile, lavender and cream room tones, cozy hygge mood, natural soft lighting", notes: "" },
  { id: "p5", title: "Kitchen morning tease", mood: "suggestive", scene: "Standing in a sunlit kitchen, wearing only an oversized white button-up shirt half-buttoned, bare legs, soft rose-pink hair in a loose messy bun, holding a strawberry, shy half-smile, morning light through sheer curtains, soft shadows, intimate casual vibe", notes: "" },
  { id: "p6", title: "Close-up blush", mood: "nsfw", scene: "Extreme close intimate portrait, face and bare shoulders, soft peachy blush across cheeks, slightly parted pink lips, honey-brown eyes looking up shyly, rose-pink hair tousled, warm candlelight, sensual and sweet, adult mood, creamy skin texture, shallow depth of field", notes: "" },
  { id: "p7", title: "Ribbon & lace vanity", mood: "suggestive", scene: "Sitting at a vanity mirror tying a soft ribbon in her rose-pink hair, wearing a cream lace bralette and soft skirt, pearl earrings, bottles and perfume softly blurred, looking back over her shoulder with a shy flirty glance, pastel aesthetic, gentle film grain", notes: "" },
  { id: "p8", title: "Late-night sheets", mood: "nsfw", scene: "In bed under rumpled cream sheets pulled up loosely, soft pastel lace underwear visible at the hip, bare midriff, lying on her side facing camera, whispering expression, soft freckles, warm pink ambient light, romantic NSFW, intimate and tender not aggressive", notes: "" },
  { id: "p9", title: "Park picnic soft", mood: "soft", scene: "Sitting on a picnic blanket in a quiet park, cream sundress with small blush floral print, soft wind in rose-pink hair, holding a flower near her face, shy smile, dappled sunlight, dreamy bokeh, lifestyle influencer aesthetic, wholesome and pretty", notes: "" },
  { id: "p10", title: "After-shower steam", mood: "nsfw", scene: "Wrapped in a soft towel loosely at the chest, wet rose-pink hair dripping, steam in a warm bathroom, looking down shyly then glancing up, water droplets on collarbones and shoulders, intimate adult atmosphere, soft diffused light, sensual and cute", notes: "" },
  { id: "p11", title: "Bathtub petals", mood: "nsfw", scene: "Relaxing in a warm bathtub scattered with soft pink rose petals, water at mid-chest, wet rose-pink hair clinging to neck and shoulders, soft freckles, shy smile, candlelight reflections on wet skin, intimate adult atmosphere, romantic and tender, creamy pastel tones", notes: "" },
  { id: "p12", title: "Kneeling pillow talk", mood: "nsfw", scene: "Kneeling on a soft bed facing camera, wearing delicate blush sheer lingerie with tiny bows, rose-pink hair in loose waves, hands resting shyly on thighs, looking up with soft bedroom eyes, warm pink lamp glow, intimate NSFW, sweet and consensual mood, cream sheets behind her", notes: "" },
  { id: "p13", title: "Unbuttoning slowly", mood: "nsfw", scene: "Sitting on the edge of the bed, slowly unbuttoning a soft cream cardigan to reveal pastel lace bralette underneath, rose-pink hair falling forward, cheeks flushed, shy half-lidded glance at camera, warm evening light, sensual undressing moment, adult content, soft and cute not aggressive", notes: "" },
  { id: "p14", title: "Morning stretch nude-adjacent", mood: "nsfw", scene: "Waking stretch in soft morning light, cream sheet slipping to the waist, bare back and shoulders, rose-pink bed-hair, looking back over her shoulder with a sleepy shy smile, soft freckles, intimate adult bedroom scene, gentle backlight, romantic NSFW, tender and private", notes: "" },
  { id: "p15", title: "Mirror lingerie try-on", mood: "nsfw", scene: "Full-length mirror selfie, trying on soft pink lace lingerie set with matching thigh garters, one hand adjusting a strap, rose-pink hair in a soft ponytail, shy bitten lip, bedroom vanity lights, intimate adult try-on vibe, pastel aesthetic, tasteful sensual NSFW", notes: "" },
  { id: "p16", title: "Strawberry taste", mood: "nsfw", scene: "Close intimate crop, sitting cross-legged on bed in soft underwear, holding a strawberry to her lips with a shy playful look, juice faintly on lower lip, rose-pink hair, warm golden lamp, adult flirtatious mood, creamy skin, soft blush everywhere, cute NSFW food tease", notes: "" },
  { id: "p17", title: "Hands & collarbone", mood: "nsfw", scene: "Intimate crop from lips to waist, bare collarbones and soft cleavage in a low sheer camisole, her own hands lightly tracing her neck and sternum, rose-pink hair ends in frame, warm candlelight, sensual self-touch, adult romantic NSFW, shy expression just in frame, soft focus", notes: "" },
  { id: "p18", title: "Shower silhouette", mood: "nsfw", scene: "Behind steamed glass shower door, soft silhouette of her body with rose-pink hair visible as color, water droplets on glass, warm bathroom light, suggestive nude silhouette, intimate adult atmosphere, artistic soft NSFW, dreamy and private, no harsh detail", notes: "" },
  { id: "p19", title: "On-the-floor pillows", mood: "nsfw", scene: "Lying on a nest of cream and blush pillows on the floor, wearing only soft pastel knee socks and delicate panties, oversized shirt open, rose-pink hair spread out, looking at camera with shy invitation, fairy lights bokeh, intimate adult vibe, cute and soft NSFW", notes: "" },
  { id: "p20", title: "Goodnight whisper close", mood: "nsfw", scene: "Extreme close pillow talk framing, bare shoulders under a shared cream blanket, face close to camera as if whispering goodnight, soft parted lips, honey-brown eyes half-lidded, rose-pink hair messy, warm nightstand lamp, romantic intimate adult mood, tender NSFW closeness", notes: "" },
  { id: "p21", title: "Stocking peel", mood: "nsfw", scene: "Sitting on the bed edge rolling down a soft blush sheer stocking, pastel lace garter visible, rose-pink hair falling over one eye, shy focused expression, warm bedroom lamp, intimate undress detail, adult sensual mood, cream and pink palette, cute not crude", notes: "" },
  { id: "p22", title: "Backless night slip", mood: "nsfw", scene: "Standing with back to camera looking over her shoulder, wearing a soft satin blush night slip with open back, rose-pink hair cascading down bare spine, soft freckles on shoulders, dim romantic lighting, intimate adult evening, elegant sensual NSFW, shy glance", notes: "" },
  { id: "p23", title: "Couch blanket tease", mood: "nsfw", scene: "On a soft couch under a blush knit blanket that has slipped, soft pastel lace bra visible, rose-pink hair messy, holding the blanket shyly at her chest, warm living-room lamp, intimate adult cozy NSFW, cute and flustered expression, cream and pink tones", notes: "" },
  { id: "p24", title: "Window rain lingerie", mood: "nsfw", scene: "Standing by a rainy window in sheer blush lingerie, city lights soft through wet glass, rose-pink hair, one hand on the glass, looking back shyly, cool blue and warm lamp mix, intimate adult mood, romantic soft NSFW, freckles visible", notes: "" },
  { id: "p25", title: "Knees-up shy nude", mood: "nsfw", scene: "Sitting on cream sheets with knees drawn up, arms wrapped softly around legs, tasteful artistic nude, rose-pink hair covering chest partially, shy eye contact, warm pink ambient light, intimate adult, soft and vulnerable NSFW, never crude, creamy skin", notes: "" },
  { id: "p26", title: "Pearl necklace only", mood: "nsfw", scene: "Close upper-body intimate portrait, wearing only a delicate pearl necklace, soft bare shoulders and chest tastefully framed, rose-pink hair over one shoulder, soft blush, honey-brown eyes looking down then up, candlelight, elegant adult NSFW, romantic and sweet", notes: "" },
  { id: "p27", title: "Yoga pants peel", mood: "nsfw", scene: "In a soft bedroom, peeling down soft blush yoga pants to reveal matching lace panties, oversized crop top riding up, rose-pink ponytail, shy giggle expression mid-motion, warm daylight, intimate adult undress tease, cute soft NSFW", notes: "" },
  { id: "p28", title: "Bed on all fours glance", mood: "nsfw", scene: "On cream bed on all fours looking back over her shoulder, soft blush lingerie set, rose-pink hair falling aside, shy inviting glance, warm lamp, intimate adult pose, tender not aggressive NSFW, pastel aesthetic, soft shadows", notes: "" },
  { id: "p29", title: "Bubble bath shoulders", mood: "nsfw", scene: "In a bubble bath, foam covering chest, bare wet shoulders and collarbones, rose-pink wet hair, soft smile, candle ring around tub, intimate adult bath mood, romantic soft NSFW, steam haze, freckles, creamy pastel", notes: "" },
  { id: "p30", title: "Shirt as dress only", mood: "nsfw", scene: "Wearing only a boyfriend white shirt unbuttoned low, nothing underneath implied tastefully, standing in doorway, rose-pink hair, biting lip shyly, morning light, intimate adult tease, soft NSFW, long bare legs, cream interior", notes: "" },
  { id: "p31", title: "Hands covering shy", mood: "nsfw", scene: "Standing nude artistic pose covering herself softly with both hands, rose-pink hair, flushed cheeks, looking aside shyly, warm studio-like bedroom light, intimate adult vulnerability, soft NSFW, tasteful and cute, freckles, cream backdrop", notes: "" },
  { id: "p32", title: "Lap blanket phone", mood: "nsfw", scene: "Sitting in someone's implied lap under a shared blanket (solo framing), soft lingerie straps visible, holding phone for a selfie, rose-pink hair, flustered cute smile, warm evening light, intimate adult closeness, soft NSFW, cozy and shy", notes: "" },
  { id: "p33", title: "Corset ribbons", mood: "nsfw", scene: "Sitting on vanity stool in a soft blush corset with ribbons half-tied, matching panties, rose-pink hair in soft curls, looking at camera through mirror, warm bulbs, intimate adult dressing ritual, elegant soft NSFW, pastel luxury", notes: "" },
  { id: "p34", title: "Sunrise sheets kick", mood: "nsfw", scene: "Lying diagonally across rumpled cream sheets at sunrise, soft nude under a translucent sheet clinging to curves, rose-pink hair, sleepy stretch, golden light, intimate adult morning, romantic soft NSFW, dreamy bokeh, freckles", notes: "" },
  { id: "p35", title: "Explicit bed invitation", mood: "nsfw", scene: "Fully nude on cream sheets, legs softly parted, one knee bent, covering almost nothing with a shy hand then moving it away, rose-pink hair, flushed face, looking at camera with embarrassed desire, warm pink lamp, explicit adult NSFW, soft cute expression, detailed skin, intimate and consensual", notes: "" },
  { id: "p36", title: "Self-touch shy", mood: "nsfw", scene: "Lying back nude, one hand between her thighs touching herself gently, other hand covering her mouth in a shy gasp, rose-pink hair spread on pillow, honey-brown eyes half-lidded, warm bedroom light, explicit masturbation NSFW, soft and cute not crude, creamy skin, freckles", notes: "" },
  { id: "p37", title: "On top riding frame", mood: "nsfw", scene: "Straddling (partner implied out of frame), nude, hands on her own thighs, soft breasts, rose-pink hair messy, biting lip, looking down shyly then at camera, motion blur subtle, warm lamp, explicit sex pose NSFW, cute flustered face, intimate adult, cream sheets", notes: "" },
  { id: "p38", title: "Oral tease close", mood: "nsfw", scene: "Kneeling close to camera at edge of bed, nude, lips parted wet, tongue tip visible, looking up with shy bedroom eyes, rose-pink hair falling forward, hands on mattress, warm light, explicit oral tease NSFW, soft cute submissive-sweet mood, detailed mouth, adult only", notes: "" },
  { id: "p39", title: "Bent over glance explicit", mood: "nsfw", scene: "Bent over the foot of the bed looking back, nude, arched back, soft ass and hips emphasized, rose-pink hair, shy inviting eye contact, warm bedroom lamp, explicit rear view NSFW, cute not degrading, detailed skin, cream sheets, intimate adult", notes: "" },
  { id: "p40", title: "Fingers glistening", mood: "nsfw", scene: "Close intimate shot of her face and hand, fingers glistening near parted lips, nude shoulders, rose-pink hair, embarrassed shy smile after touching herself, warm candlelight, explicit afterglow NSFW, soft cute expression, adult consensual, creamy skin", notes: "" },
  { id: "p41", title: "Missionary under him frame", mood: "nsfw", scene: "On her back nude, legs around implied partner, soft breasts, arms above head loosely, rose-pink hair, moaning-shy expression looking at camera, sheets tangled, warm light, explicit sex missionary NSFW, tender and sweet, adult only, freckles, intimate", notes: "" },
  { id: "p42", title: "Shower pressed glass", mood: "nsfw", scene: "Nude pressed lightly to steamy shower glass from inside, breasts and hips soft against glass, wet rose-pink hair, eyes closed then opening shyly, water running, explicit wet nude NSFW, artistic and intimate, adult, soft lighting through steam", notes: "" },
  { id: "p43", title: "Toy shy first time", mood: "nsfw", scene: "Sitting on bed nude, holding a small pastel vibrator shyly against her thigh, cheeks deep blush, rose-pink hair, looking away then at camera, cream sheets, warm lamp, explicit toy tease NSFW, cute nervous energy, adult consensual, soft aesthetic", notes: "" },
  { id: "p44", title: "Creampie aftermath soft", mood: "nsfw", scene: "Lying on back after sex, nude, soft stomach and thighs, subtle glistening between legs tastefully shown, rose-pink hair messy, dazed happy shy smile, warm nightstand light, explicit aftermath NSFW, tender aftercare mood, adult only, creamy skin, freckles", notes: "" },
  { id: "p45", title: "Cowgirl grind close", mood: "nsfw", scene: "Close crop cowgirl, nude torso and hips grinding, soft breasts bouncing subtly, hands on chest of implied partner, rose-pink hair sticking to sweaty neck, flustered cute moan-face, warm light, explicit sex NSFW, sweet and shy, adult, detailed skin", notes: "" },
  { id: "p46", title: "Spread for camera shy", mood: "nsfw", scene: "Sitting at edge of bed nude, legs spread toward camera, one hand spreading herself shyly, face turned partially away with embarrassed blush, rose-pink hair, warm pink light, explicit pussy focus NSFW, still cute soft vibe, adult consensual, cream sheets", notes: "" },
  { id: "p47", title: "Deepthroat attempt shy", mood: "nsfw", scene: "Kneeling nude, taking a thick cock deep in her mouth, tears of effort glistening, rose-pink hair held back loosely, looking up with shy watery eyes, saliva strands, warm bedroom light, explicit deepthroat NSFW, cute embarrassed expression, adult consensual, detailed mouth and cock", notes: "" },
  { id: "p48", title: "Doggy creampie drip", mood: "nsfw", scene: "On all fours after being fucked, nude, ass up, cum dripping from her pussy down her thighs, looking back flushed and shy, rose-pink hair messy, cream sheets, warm lamp, explicit creampie aftermath NSFW, soft cute face, adult only, detailed fluids", notes: "" },
  { id: "p49", title: "Ahegao almost", mood: "nsfw", scene: "Close face during orgasm, nude shoulders, tongue slightly out, crossed soft eyes almost, heavy blush, tears of pleasure, rose-pink hair stuck to cheeks, explicit ahegao-lite NSFW still cute not grotesque, warm light, adult consensual, intimate", notes: "" },
  { id: "p50", title: "Double toy fill", mood: "nsfw", scene: "On her back nude, pastel dildo in her pussy and small plug in her ass, legs spread, hands covering her face shyly between fingers, rose-pink hair, warm pink light, explicit double penetration toys NSFW, cute overwhelmed expression, adult consensual, cream sheets", notes: "" },
  { id: "p51", title: "Facial finish soft", mood: "nsfw", scene: "Kneeling nude after facial, cum on freckled cheeks and parted lips, eyes closed then opening shyly, rose-pink hair, soft smile embarrassed, warm light, explicit cum on face NSFW, still sweet and cute, adult consensual, detailed skin and fluids", notes: "" },
  { id: "p52", title: "Squirting surprise", mood: "nsfw", scene: "On her back mid-orgasm, nude, clear squirt spraying toward camera, legs trembling, rose-pink hair, shocked shy moan-face, wet sheets, warm lamp, explicit female ejaculation NSFW, cute surprised expression, adult consensual, dynamic motion", notes: "" },
  { id: "p53", title: "Mating press folded", mood: "nsfw", scene: "Folded in mating press, knees by ears, nude, cock buried deep in her pussy, soft breasts pressed, rose-pink hair fanned out, flustered cute moan looking at camera, warm light, explicit deep penetration sex NSFW, tender intensity, adult only", notes: "" },
  { id: "p54", title: "Cum in mouth show", mood: "nsfw", scene: "Close-up, mouth open showing cum on tongue, nude collarbones, rose-pink hair, shy eye contact before swallowing, warm candlelight, explicit cumplay NSFW, soft cute expression, adult consensual, detailed tongue and fluids", notes: "" },
  { id: "p55", title: "Public risk balcony", mood: "nsfw", scene: "On a private night balcony, skirt up, panties aside, fingers in her wet pussy, other hand gripping railing, rose-pink hair in wind, nervous aroused glance at camera, city bokeh, explicit risky masturbation NSFW, cute scared-excited face, adult, no bystanders in frame", notes: "" },
  { id: "p56", title: "Throat bulge hint", mood: "nsfw", scene: "Profile close-up deepthroat, slight throat bulge, nude, hand on shaft, rose-pink hair, eyes watering softly, explicit extreme oral NSFW, still soft lighting and cute framing, adult consensual, detailed anatomy", notes: "" },
  { id: "p57", title: "Prone bone sheets", mood: "nsfw", scene: "Lying flat on stomach being fucked prone bone, nude, ass raised slightly, face turned to camera with pillow muffling shy moans, rose-pink hair, cream sheets, warm light, explicit prone sex NSFW, soft cute expression, adult, detailed penetration", notes: "" },
  { id: "p58", title: "Filled and plugged sleep", mood: "nsfw", scene: "Asleep-looking aftercare pose, nude under sheet half-off, cum leaking, small pink plug still in, peaceful shy smile, rose-pink hair, nightstand lamp, explicit filled plugged NSFW, tender soft vibe, adult consensual, intimate bedroom", notes: "" },
];

export const STARTER_WEEK = [
  { id: "c1", day: "Monday", idea: "Soft golden-hour window seat portrait + shy cozy caption", status: "idea" },
  { id: "c2", day: "Tuesday", idea: "Mirror selfie in silk robe — suggestive tease, soft lighting", status: "idea" },
  { id: "c3", day: "Wednesday", idea: "Cozy rainy-night hoodie reel / still + grateful caption", status: "idea" },
  { id: "c4", day: "Thursday", idea: "Kitchen morning oversized shirt — flirty SFW-leaning", status: "idea" },
  { id: "c5", day: "Friday", idea: "Vanity ribbon & lace — getting-ready vibe", status: "idea" },
  { id: "c6", day: "Saturday", idea: "NSFW bedtime / sheets set for close followers", status: "idea" },
  { id: "c7", day: "Sunday", idea: "Park picnic soft lifestyle + week wrap thank-you caption", status: "idea" },
];

